[package]
name = "sub-script"
version = "0.8.0"
authors = ["Robert G. Jakabosky <rjakabosky+neopallium@neoawareness.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Scripting tool for Substrate chains"
keywords = ["scripting", "blockchain", "substrate", "rhai"]
repository = "https://github.com/PolymeshAssociation/sub-script"
homepage = "https://github.com/PolymeshAssociation/sub-script"

[patch.crates-io]
frame-support = { git = "https://github.com/PolymeshAssociation/substrate", branch = "polymesh-monthly-2022-05" }
frame-system = { git = "https://github.com/PolymeshAssociation/substrate", branch = "polymesh-monthly-2022-05" }
sp-application-crypto = { git = "https://github.com/PolymeshAssociation/substrate", branch = "polymesh-monthly-2022-05" }
sp-arithmetic = { git = "https://github.com/PolymeshAssociation/substrate", branch = "polymesh-monthly-2022-05" }
sp-io = { git = "https://github.com/PolymeshAssociation/substrate", branch = "polymesh-monthly-2022-05" }
sp-core = { git = "https://github.com/PolymeshAssociation/substrate", branch = "polymesh-monthly-2022-05" }
sp-std = { git = "https://github.com/PolymeshAssociation/substrate", branch = "polymesh-monthly-2022-05" }
sp-version = { git = "https://github.com/PolymeshAssociation/substrate", branch = "polymesh-monthly-2022-05" }
sp-runtime = { git = "https://github.com/PolymeshAssociation/substrate", branch = "polymesh-monthly-2022-05" }
sp-runtime-interface = { git = "https://github.com/PolymeshAssociation/substrate", branch = "polymesh-monthly-2022-05" }

[dependencies]
anyhow = "1.0.44"
log = "0.4"
dotenv = "0.15"
env_logger = "0.9"
structopt = "0.3.25"

# Client
serde_json = { version = "1.0", features = ["preserve_order"] }
serde = "1.0"
dashmap = "5.3"
url = "2.2"
ws = { version = "0.9", features = [ "ssl" ] }
crossbeam-channel = "0.5"

# substrate
sp-core = { version = "6.0", default-features = false }
sp-version = { version = "5.0", default-features = false }
sp-runtime = { version = "6.0", default-features = false }
frame-support = { version = "4.0.0-dev", default-features = false }
frame-metadata = { version = "15.0.0", default-features = false, features = ["std"] }
parity-scale-codec = "3.0"

scale-info = { version = "2.0", default-features = false, optional = true }

# rhai
rhai = { version = "=1.6.1", default-features = false, features = ["sync", "only_i64", "no_float", "decimal", "serde", "metadata"]}
indexmap = "1.8"

hex = "0.4"
rust_decimal = "1.23"
smartstring = "1.0"

# libp2p
bs58 = { version = "0.4.0", optional = true }
libp2p-core = { version = "0.32.1", optional = true }

# Ledger
ledger-transport-hid = { version = "0.9.0", optional = true }
ledger-apdu = { version = "0.9.0", optional = true }

# Polymesh
confidential_identity_v1 = { package = "confidential_identity", git = "https://github.com/PolymeshAssociation/cryptography.git", default-features = false, branch = "confidential-identity-v1", optional = true }
polymesh-primitives = { git = "https://github.com/PolymeshAssociation/Polymesh", branch = "develop", default-features = false, optional = true }

[features]
default = [ "std", "ledger", "polymesh", "v12", "v13", "v14", "libp2p" ]

libp2p = [ "bs58", "libp2p-core" ]

v12 = ["frame-metadata/v12"]
v13 = ["frame-metadata/v13"]
v14 = ["frame-metadata/v14", "scale-info"]

# Ledger
ledger = [
	"ledger-transport-hid",
	"ledger-apdu",
]

# Polymesh
polymesh = [
	"confidential_identity_v1",
	"polymesh-primitives",
]

no_std = [
	"confidential_identity_v1/no_std",
	"polymesh-primitives/no_std",
	"polymesh-primitives/u64_backend",
]

std = [
	"confidential_identity_v1/std",
	"polymesh-primitives/std",
	"polymesh-primitives/u64_backend",
]
